<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseAppHost>true</UseAppHost>
    <StartupObject>FileMill.Program</StartupObject>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_EXAMPLE_\**" />
    <Page Remove="_EXAMPLE_\**" />
    <ApplicationDefinition Remove="_EXAMPLE_\**" />
    <Resource Remove="_EXAMPLE_\**" />
    <EmbeddedResource Remove="_EXAMPLE_\**" />
    <None Remove="_EXAMPLE_\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.18.2" />
  </ItemGroup>

  <Target Name="CopyTools" AfterTargets="Build">
    <ItemGroup>
      <ToolsFiles Include="tools\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(ToolsFiles)" DestinationFolder="$(OutputPath)\tools\%(RecursiveDir)" SkipUnchangedFiles="true" Condition="Exists('tools')" />
  </Target>

</Project>
